"""Core Avellaneda-Stoikov quote formulas.

This module intentionally contains only the clean model math. It does not know
about order books, fills, fees, latency, or backtesting.
"""

from __future__ import annotations

from dataclasses import dataclass
from math import log


@dataclass(frozen=True) # frozen means once created the object cant be modified
class ModelParameters:
    """Parameters used by the approximate Avellaneda-Stoikov formula.

    Attributes:
        gamma: Risk-aversion parameter. Higher values penalize inventory harder.
        sigma: Price volatility over sqrt(time). Must use units consistent with
            the chosen horizon.
        horizon: Remaining control horizon.
        k: Order-arrival decay parameter. Higher values mean fill probability
            falls faster as quotes move away from the mid-price.
    """

    gamma: float
    sigma: float
    horizon: float
    k: float


@dataclass(frozen=True)
class Quote:
    """Bid/ask quote generated by the model."""

    bid: float
    ask: float
    reservation_price: float
    spread: float


def _validate_market_state(mid_price: float) -> None:
    if mid_price <= 0:
        raise ValueError("mid_price must be positive.")


def _validate_params(params: ModelParameters) -> None:
    if params.gamma <= 0:
        raise ValueError("gamma must be positive.") # risk aversion cant be 0 or negative
    if params.sigma < 0:
        raise ValueError("sigma cannot be negative.") # vol can be 0
    if params.horizon < 0:
        raise ValueError("horizon cannot be negative.") # horizon also can be 0
    if params.k <= 0:
        raise ValueError("k must be positive.") # k must be positive cos model assumes fill probability decays as quote distance increases.



def reservation_price(mid_price: float, inventory: float, params: ModelParameters) -> float:
    """Return the inventory-adjusted reservation price.

    The reservation price is the center of the market maker's quotes. Long
    inventory pushes it below the mid-price; short inventory pushes it above.
    """

    # we check that the inputs are valid before doing any math
    _validate_market_state(mid_price=mid_price)
    _validate_params(params)

    # this is the inventory-control part of the model. If we are long, this
    # subtracts from the mid-price so our quotes lean toward selling inventory.
    # but if we are short, inventory is negative, so the reservation price moves up.
    return mid_price - inventory * params.gamma * (params.sigma**2) * params.horizon


def optimal_spread(params: ModelParameters) -> float:
    """Return the approximate Avellaneda-Stoikov optimal bid-ask spread."""

    _validate_params(params)

    # Wider quotes compensate us for holding risky inventory. This grows when
    # volatility, risk aversion, or the control horizon increases.
    inventory_risk_component = params.gamma * (params.sigma**2) * params.horizon

    # This part comes from the assumed fill intensity: lambda(delta)=A*exp(-k*delta).
    # It balances quoting far enough to earn spread against quoting close enough
    # that market orders are still likely to reach us.

    execution_component = (2.0 / params.gamma) * log(1.0 + params.gamma / params.k)
    return inventory_risk_component + execution_component


def generate_quote(mid_price: float, inventory: float, params: ModelParameters) -> Quote:
    """Generate a bid and ask quote around the reservation price."""

    # first we choose the quote center based on our current inventory
    center = reservation_price(mid_price=mid_price, inventory=inventory, params=params)

    # then choose the total bid-ask width. The bid and ask each take half 
    spread = optimal_spread(params)
    half_spread = spread / 2.0

    # the model quotes around the reservation price, not around the
    # market mid-price. this is the key A-S inventory adjustment
    return Quote(
        bid=center - half_spread,
        ask=center + half_spread,
        reservation_price=center,
        spread=spread,
    )

